import bcrypt from "bcrypt";

export const users = [
  {
    firstName: "test-firstName",
    lastName: "test-lastName",
    email: "test@gmail.com",
    phone: "test-phone-123-456-7890",
    confirmed: 1,
    password: bcrypt.hashSync("123456",10),
  },
  {
    firstName: "Nealy",
    lastName: "Elintune",
    email: "nelintune0@acquirethisname.com",
    phone: "666-861-9327",
    confirmed: 1,
    password: bcrypt.hashSync("password",10),
  },
  {
    firstName: "Kimberly",
    lastName: "Strangeways",
    email: "kstrangeways1@dell.com",
    phone: "780-409-2805",
    confirmed: 1,
    password: bcrypt.hashSync("password",10),
  },
  {
    firstName: "Abbie",
    lastName: "Pays",
    email: "apays2@independent.co.uk",
    phone: "460-557-2683",
    confirmed: 1,
    password: bcrypt.hashSync("password",10),
  },
  {
    firstName: "Flinn",
    lastName: "Jaukovic",
    email: "fjaukovic3@posterous.com",
    phone: "893-391-0432",
    confirmed: 1,
    password: bcrypt.hashSync("password",10),
  },
  {
    firstName: "Betty",
    lastName: "Harroll",
    email: "bharroll4@twitter.com",
    phone: "262-236-5998",
    confirmed: 1,
    password: bcrypt.hashSync("password",10),
  },
  {
    firstName: "Baryram",
    lastName: "Scocroft",
    email: "bscocroft5@craigslist.org",
    phone: "858-311-9058",
    confirmed: 1,
    password: bcrypt.hashSync("password",10),
  },
  {
    firstName: "Nikos",
    lastName: "Corps",
    email: "ncorps6@liveinternet.ru",
    phone: "266-872-3565",
    confirmed: 1,
    password: bcrypt.hashSync("password",10),
  },
  {
    firstName: "Roth",
    lastName: "Crispe",
    email: "rcrispe7@naver.com",
    phone: "887-466-3621",
    confirmed: 1,
    password: bcrypt.hashSync("password",10),
  },
  {
    firstName: "Jareb",
    lastName: "Haugg",
    email: "jhaugg8@apache.org",
    phone: "602-889-2294",
    confirmed: 1,
    password: bcrypt.hashSync("password",10),
  },
  {
    firstName: "Staford",
    lastName: "Rappoport",
    email: "srappoport9@canalblog.com",
    phone: "851-869-5306",
    confirmed: 1,
    password: bcrypt.hashSync("password",10),
  },
];
